CREATE TABLE PRODUCT (ID INT PRIMARY KEY, NAME VARCHAR(255), DESCRIPTION VARCHAR(255), COST NUMERIC);

CREATE TABLE REVIEW (ID INT PRIMARY KEY, PRODUCT_ID INT, REVIEW VARCHAR(255), REVIEW_DATE DATE,
                     FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID))

CREATE SEQUENCE product_id_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE review_id_seq START WITH 2000 INCREMENT BY 1;